name: taskmaster
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # dependencies
  cupertino_icons: ^1.0.6

  # fonts
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # dev dependencies
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

 # Assets
  assets:
    - assets/icons/
    - assets/images/
